package pearl.ch.services.config.constants;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;

import lombok.Getter;

@Getter
@Configuration
public class UnsubscribeEncryptionConfig {

	private String PEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY;

	private String PEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV;

	private String CASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY;

	private String CASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV;

	private String NATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY;

	private String NATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV;

	@Value("${PEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY}")
	public void setPEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY(String pEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY) {
		PEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY = pEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY;
	}

	@Value("${PEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV}")
	public void setPEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV(String pEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV) {
		PEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV = pEARL_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV;
	}

	@Value("${CASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY}")
	public void setCASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY(String cASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY) {
		CASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY = cASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY;
	}

	@Value("${CASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV}")
	public void setCASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV(String cASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV) {
		CASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV = cASATIVO_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV;
	}

	@Value("${NATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY}")
	public void setNATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY(String nATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY) {
		NATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY = nATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_KEY;
	}

	@Value("${NATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV}")
	public void setNATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV(String nATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV) {
		NATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV = nATURA_UNSUBSCRIBE_TOKEN_ENCRYPTION_IV;
	}
}
